version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: directorio_backend
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///./test.db
    volumes:
      - ./backend:/app
    restart: unless-stopped
