"""Add estado to empresas

Revision ID: 52cef98e13af
Revises: 86b7b30ce912
Create Date: 2026-05-28 10:23:05.149214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52cef98e13af'
down_revision: Union[str, Sequence[str], None] = '86b7b30ce912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.add_column('empresas', sa.Column('estado', sa.String(length=20), server_default='activa', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'estado')
    pass
    # ### end Alembic commands ###
